# Generated by Django 5.2 on 2025-04-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('Tiny', 'a'), ('Small', 'b'), ('Medium', 'c'), ('Large', 'd')], max_length=10),
        ),
    ]
